# Generated by Django 4.1.3 on 2023-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_users_last_login"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.AlterField(
            model_name="users",
            name="last_login",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
